meta_product_name: "OpenPolicy Europe"
meta_title: "OpenPolicy Europe - understand and engage with policymaking"
meta_description: "Policymaking sounds overcomplicated? You don't know how to impact it? Explore your digital hub for understanding and engaging with policymaking."
meta_image: "flag-eu-square.jpeg" # in `app/assets/images/`
# twitter_account: "@product_twitter_account" # required for Twitter Cards
